services:
  - type: web
    name: RSA Quote App
    env: node
    branch: main
    startCommand: node .output/server/index.mjs
    buildCommand: npm install && npm run build
    envVars:
      - key: NITRO_PRESET
        value: render-com
